<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="multipopulation"
    nsURI="http:///org/eclipse/stem/diseasemodels/multipopulation.ecore" nsPrefix="org.eclipse.stem.diseasemodels.multipopulation">
  <eClassifiers xsi:type="ecore:EClass" name="MultiPopulationSIDiseaseModel" eSuperTypes="../../org.eclipse.stem.diseasemodels/model/standard.ecore#//StandardDiseaseModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="populationGroups" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.stem.core/model/common.ecore#//StringValueList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transmissionRate" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.stem.core/model/common.ecore#//DoubleValueMatrix"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recoveryRate" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.stem.core/model/common.ecore#//DoubleValueList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infectiousMortalityRate"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.stem.core/model/common.ecore#//DoubleValueList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="physicallyAdjacentInfectiousProportion"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roadNetworkInfectiousProportion"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
