<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="standard"
    nsURI="http:///org/eclipse/stem/populationmodels/standard" nsPrefix="org.eclipse.stem.populationmodels.standard">
  <eClassifiers xsi:type="ecore:EClass" name="PopulationModel" abstract="true" eSuperTypes="../../org.eclipse.stem.core/model/model.ecore#//NodeDecorator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="populationIdentifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="human"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="HumanPopulationModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardPopulationModel" eSuperTypes="#//PopulationModel #//IntegrationDecorator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthRate" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deathRate" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timePeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="86400000"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PopulationModelLabel" eSuperTypes="../../org.eclipse.stem.core/model/graph.ecore#//DynamicNodeLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="populationLabel" eType="ecore:EClass ../../org.eclipse.stem.definitions/model/labels.ecore#//PopulationLabel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="populationIdentifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardPopulationModelLabel" eSuperTypes="#//PopulationModelLabel #//IntegrationLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deltaValue" eType="#//StandardPopulationModelLabelValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probeValue" eType="#//StandardPopulationModelLabelValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tempValue" eType="#//StandardPopulationModelLabelValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalValue" eType="#//StandardPopulationModelLabelValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorScale" eType="#//StandardPopulationModelLabelValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationLabel" instanceClassName="org.eclipse.stem.core.graph.IntegrationLabel"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationLabelValue" instanceClassName="org.eclipse.stem.core.graph.IntegrationLabelValue"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationDecorator" instanceClassName="org.eclipse.stem.core.model.IntegrationDecorator"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PopulationModelLabelValue" eSuperTypes="../../org.eclipse.stem.core/model/graph.ecore#//LabelValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardPopulationModelLabelValue" eSuperTypes="#//PopulationModelLabelValue #//IntegrationLabelValue">
    <eOperations name="adjustDelta" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="value" eType="#//IntegrationLabelValue"/>
    </eOperations>
    <eOperations name="getAdditions" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eOperations name="getSubstractions" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incidence" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="births" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deaths" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="density" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" defaultValueLiteral="0.0" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StochasticStandardPopulationModel" eSuperTypes="#//StandardPopulationModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gain" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.01"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DemographicPopulationModel" eSuperTypes="#//StandardPopulationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="populationGroups" lowerBound="1"
        upperBound="-1" eType="#//PopulationGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PopulationGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fraction" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.5"/>
  </eClassifiers>
</ecore:EPackage>
