// ISimulationListener.java
package org.eclipse.stem.jobs.simulation;

/*******************************************************************************
 * Copyright (c) 2006, 2008 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

import org.eclipse.stem.jobs.execution.IExecutableListenerSync;

/**
 * This interface is implemented by classes that want to listen to events
 * generated by a {@link Simulation}. The thread running the {@link Simulation}
 * will wait until the {@link #simulationChangedSync(SimulationEvent)} method
 * returns before it continues execution.
 * 
 * @see ISimulation
 */
public interface ISimulationListenerSync extends IExecutableListenerSync {
	/**
	 * @param event
	 *            the event that records what happened to the {@link Simulation}.
	 */
	void simulationChangedSync(SimulationEvent event);
} // ISimulationListenerSync
