// IBatchListener.java
package org.eclipse.stem.jobs.batch;

/*******************************************************************************
 * Copyright (c) 2008 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

import org.eclipse.stem.jobs.execution.IExecutableListener;


/**
 * This interface is implemented by classes that want to listen to events
 * generated by a {@link IBatch}.
 * 
 * @see IBatch
 */
public interface IBatchListener extends IExecutableListener {

	/**
	 * @param event
	 *            the {@link BatchEvent} the specifies what changed in the
	 *            {@link IBatch}.
	 */
	void batchChanged(BatchEvent event);

} // IBatchListener
